name: Sync Issue Labels to PR

permissions:
  pull-requests: write
  contents: read
  issues: write

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Find linked issue and copy labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;

            // PR 상세 정보 가져오기
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            const body = pr.body || '';
            const issueNumberMatch = body.match(/#(\d+)/);

            if (!issueNumberMatch) {
              console.log("❗ PR body에 연결된 이슈가 없습니다.");
              return;
            }

            const issueNumber = parseInt(issueNumberMatch[1], 10);

            // 이슈 상세 정보 가져오기
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });

            const labels = issue.labels.map(label => label.name);

            if (labels.length === 0) {
              console.log(`❗ 이슈 #${issueNumber}에 라벨이 없습니다.`);
              return;
            }

            // PR에 라벨 추가하기
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: labels,
            });

            console.log(`✅ 이슈 #${issueNumber}의 라벨 [${labels.join(", ")}] 을 PR에 복사했습니다.`);
