name: Sync Issue Labels to PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Find linked issue
        id: find-issue
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const body = pr.data.body;
            const issueNumberMatch = body.match(/#(\d+)/);
            if (!issueNumberMatch) {
              console.log("No linked issue found.");
              return;
            }

            const issueNumber = issueNumberMatch[1];

            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });

            const labels = issue.data.labels.map(label => label.name);

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: labels,
            });

